
;==============================================================================
; 
;==============================================================================

.define nameEntryCursorPos $2760
.define nameEntryCurrentPutIndex $2761
.define nameEntryInputArray $3AC5

.define oldPasswordLen 6
.define newPasswordLen 12

.define passwordSpaceValue $00
.define passwordNullValue $FF

.define passwordNumIndices $1D

.define passwordIndexErase $1B
.define passwordIndexEnd $1C

.define passwordCursorBaseTileX $12
.define passwordCursorBaseTileY $02+2
.define passwordCharsPerRow 6
.define passwordCharsXSpacing 2
.define passwordCharsYSpacing 2
.define passwordNumRows 5

.define passwordDisplayExtraXOffset -4
